#!/usr/bin/expect -f
#
# Copyright (C) SUSE LLC 2019, all rights reserved.
#
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) version 3.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
# License for more details.

# cut+boot the simple-example runner and wait for the greeting string

set timeout 60
spawn ./rapido cut simple-example
expect {
	timeout {exit 1}; eof {exit 2}
	"Rapido scratch VM running. Have a lot of fun..."
}
