#!/usr/bin/expect -f
# SPDX-License-Identifier: (LGPL-2.1 OR LGPL-3.0)
# Copyright (C) SUSE LLC 2019-2023, all rights reserved.

# simple-example runner with separate cut + boot invocations

set timeout 60
spawn ./rapido cut -B simple-example
expect {
	timeout {exit 1}
	"myinitrd written"
}
expect {
	timeout {exit 1}
	eof
}
spawn ./rapido boot
expect {
	timeout {exit 1}; eof {exit 2}
	"Rapido scratch VM running"
}
send "reboot\r"
expect {
	timeout {exit 1}; eof {exit 2}
	"Rapido scratch VM running"
}
send "cd root\r"
expect {
	timeout {exit 1}; eof {exit 2}
	"/root"
}
send "shutdown\r"
expect eof {exit 0}
exit 5
