#!/usr/bin/expect -f
#
# Copyright (C) SUSE LLC 2019, all rights reserved.
#
# This library is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation; either version 2.1 of the License, or
# (at your option) version 3.
#
# This library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
# License for more details.

# simple-example runner with separate cut + boot invocations

set timeout 60
spawn ./rapido cut -B simple-example
expect {
	timeout {exit 1}
	"dracut: *** Creating initramfs image file"
}
expect {
	timeout {exit 1}
	eof
}
spawn ./rapido boot
expect {
	timeout {exit 1}; eof {exit 2}
	"Rapido scratch VM running. Have a lot of fun..."
}
send "reboot\r"
expect {
	timeout {exit 1}; eof {exit 2}
	"Rapido scratch VM running. Have a lot of fun..."
}
send "cd root\r"
expect {
	timeout {exit 1}; eof {exit 2}
	"/root"
}
send "shutdown\r"
expect eof {exit 0}
exit 5
