name: CI

on:
  pull_request:

# "cargo" default package results in v1.75, which doesn't support v4 lock files
# "cargo test uses lib and bins only, as doc test breaks for some reason
# chmod vmlinuz-`uname -r` as it's 0600 by default
# chmod /dev/kvm to allow non-root QEMU to use it
# if building distro config install: libdw-dev libssl-dev
jobs:
  test:
    # aarch64 github runners don't provide kvm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install rust and kernel build tools
        run: |
          case "$(uname -m)" in
          x86_64)
            export QEMU_SYSTEM=qemu-system-x86
            ;;
          aarch64)
            export QEMU_SYSTEM=qemu-system-aarch64
            ;;
          *)
            exit 1
            ;;
          esac
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends --no-install-suggests \
            cargo-1.85 rustc "$QEMU_SYSTEM" qemu-utils expect \
            make flex bison libelf-dev
      - name: cargo test
        run: |
          cargo-1.85 test --offline --lib --bins
          pushd src/cpio
          cargo-1.85 test --offline --lib --bins
          popd
          pushd src/kv-conf/
          cargo-1.85 test --offline --lib --bins
          popd
      - name: build and setup rapido net
        run: |
          cargo-1.85 build --offline --release
          cp -r net-conf.example/ net-conf
          sudo EDITOR=cat ./rapido setup-network -o $USER -b rapido-br -a "192.168.155.10/24"
          sudo chmod 0644 /boot/vmlinuz-*
          sudo chmod 0666 /dev/kvm
      - name: boot host kernel VM
        run: |
         ./rapido cut -B -x "ping -c3 192.168.155.10 && echo test passed; exit" simple-network
         ./target/release/lscpio initrds/myinitrd
         ./rapido boot
      - name: run rapido selftests with host kernel
        run: |
          ./selftest/selftest.sh
      - name: clone and build mainline kernel
        run: |
          git clone --depth 1 -b master https://github.com/torvalds/linux ${HOME}/linux
          cp kernel/fstests_btrfs_zram.defconfig ${HOME}/linux/.config
          pushd ${HOME}/linux
          make olddefconfig
          make -j$(nproc)
          make modules_install INSTALL_MOD_PATH=./mods
          # this gives us modules.dep, etc. which rapido needs.
          # XXX should come with modules_install but doesn't... perhaps due to no modules?
          objtree=./ INSTALL_MOD_PATH=./mods ./scripts/depmod.sh "$(cat include/config/kernel.release)"
          popd
      - name: boot mainline kernel VM
        run: |
          printf "KERNEL_SRC=${HOME}/linux\nKERNEL_INSTALL_MOD_PATH=${HOME}/linux/mods\n" > rapido.conf
          ./rapido cut -x "cat /proc/filesystems; exit" simple-network
      - name: run rapido selftests with mainline kernel
        run: |
          # selftests creates its own rapido.conf, considering KERNEL_X envs
          export KERNEL_SRC=${HOME}/linux KERNEL_INSTALL_MOD_PATH=${HOME}/linux/mods
          ./selftest/selftest.sh
